---
title:               derek 
tagline:             Internet stuff.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Derek Dahmer
twitter:             derekdahmer
github:              ddgromit
email:               derekdahmer@gmail.com
google_analytics_id: UA-37250640-1
disqus_shortname:    <%= ENV.fetch("disqus_shortname") { "" } %>
